services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: DevPassword
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data/pgdata
volumes:
  postgresdata:
