name: Clean Main of Git and push to gitless

on:
  push:
    branches: [ "main" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3.4.0
        with:
          ref: main
      - name: get Submodule
        run: git submodule update --init --recursive
      - name: Rename folder
        run: cp -r rockstar rockstar-temp
      - name: Remove rockstar from git
        run: git rm rockstar
      - name: Move it back
        run: mv rockstar-temp rockstar
      - name: Export
        run: git archive --format=tar main | bzip2 >output.tar.gz
      - name: Upload Asset
        uses: actions/upload-artifact@v3.1.2
        with:
          name: export
          path: ./output.tar.gz
  update-main:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout gitless branch
        uses: actions/checkout@v3.4.0
        with:
          ref: gitless
      - name: Import Asset
        uses: actions/download-artifact@v2
        with:
          name: export
          path: ./
      - name: Unzip output
        run: tar -xvf output.tar.gz
      - name: List files
        run: ls rockstar
      - name: Commit && Push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config rebase.autostash true
          git config pull.rebase true
          git add *
          git commit -m "Update gitless Branch" || true
          git pull
          git push
